### ISSUE TITLE
Adding a sproc using create proc doesn't trigger script update

### ISSUE THREAD

**Issue by robbaman** [bradymholt/dbup-sqlserver-scripting#10]
When an update script contains a `create proc` command to create a stored procedure (as opposed to `create procedure`) the `DbObjectScripter` doesn't pick it up because it's RegEx only looks for PROCEDURE.

I'll try to create a PR at some point if I have the time...

**Comment by bradymholt** [comment]
Fixed by https://github.com/bradymholt/dbup-sqlserver-scripting/pull/23
