### ISSUE TITLE
Ordering created definitions

### ISSUE THREAD

**Issue by simonpinn** [bradymholt/dbup-sqlserver-scripting#11]
If the definitions were ordered by dependency then it would be possible to run the definition scripts using a DbUp upgrader against a blank database. This would be great for creating a new database from the schema definition without the need for a initialisation script, especially if the definitions have been generated from an existing database.

As a basic example, it'd be great to be able to do the following:
```
...
            var scripts = Directory.GetFiles("../../Definitions", "*.sql", SearchOption.AllDirectories)
                    .Select(x => new SqlScript(Path.GetFileName(x), File.ReadAllText(x).Replace("SET ANSI_NULLS ON", string.Empty).Replace("SET QUOTED_IDENTIFIER ON", string.Empty)));

            var initial = DeployChanges.To
                    .SqlDatabase(connectionString)
                    .WithScripts(scripts)
                    .LogToConsole()
                    .Build();

            var initResult = initial.PerformUpgrade();
...
```

However due to dependencies (foreign keys for example), the scripts need to be executed in order, this could be done at the time of creating the definition scripts.

Has this been considered? Great libray btw.

**Comment by bradymholt** [comment]
I would love to have the ability to create the database from scratch.  I think this would be ideal.  I would surely welcome a PR!

**Comment by simonpinn** [comment]
Hi @bradyholt  

Just raised a PR, lets you run a definition against a blank db, let me know your thoughts.

cheers
