### ISSUE TITLE
Functions are being duplicated as UserDefinedTypes

### ISSUE THREAD

**Issue by efranzinelli** [bradymholt/dbup-sqlserver-scripting#14]
When running `Start-DatabaseScript`, user defined functions are being created twice - firstly in the Definitions\Function folder and also in the Definitions\UserDefinedTypes folder. 

This then causes the `New-InitialScript` command to fail due to a `StackOverflowException` as it walks the dependency tree - two items with an identical name (although different paths). 

From the Call Stack: 
`DbUp.Support.SqlServer.Scripting.dll!DbUp.Support.SqlServer.Scripting.DefinitionScriptProvider.AddParent(System.Collections.Generic.List<DbUp.Support.SqlServer.Scripting.DefinitionScriptProvider.Script> result, DbUp.Support.SqlServer.Scripting.DefinitionScriptProvider.Script current)`

If I comment out lines 229-236 and 268-272 in DbObjectScripter.cs (https://github.com/bradyholt/dbup-sqlserver-scripting/blob/master/DbUp.Support.SqlServer.Scripting/DbObjectScripter.cs#L229), the duplications stop. I'm not really sure why UDFs are being considered to be types here but they are definitely being generated in two places which is causing conflicts.

**Comment by simonpinn** [comment]
Recreated it here https://github.com/bradyholt/dbup-sqlserver-scripting/pull/12#issuecomment-304020909 - doesn't appear related to the latest release, tested after downgrade too

**Comment by bradymholt** [comment]
@efranzinelli @simonpinn I think the scripting of user defined types is scripting functions as well, so this is causing duplicated scripting of functions.  I currently don't have a good setup to fix/test this.  Would either of you be able to experiment with omitting this bit: https://github.com/bradyholt/dbup-sqlserver-scripting/blob/master/DbUp.Support.SqlServer.Scripting/DbObjectScripter.cs#L65-L69 and see if the scripting of user defined types (https://github.com/bradyholt/dbup-sqlserver-scripting/blob/master/DbUp.Support.SqlServer.Scripting/DbObjectScripter.cs#L77-L81) outputs the functions.  If so, we may be able to omit https://github.com/bradyholt/dbup-sqlserver-scripting/blob/master/DbUp.Support.SqlServer.Scripting/DbObjectScripter.cs#L65-L69  altogether.

**Comment by efranzinelli** [comment]
I have just confirmed that commenting lines 65-69 (and 87) in DbObjectScripter.cs results in all functions being outputted to the UserDefinedTypes folder and the absence of the Functions folder - hence no duplications. Proceeding to run the command `New-InitialScript` is now successful.

**Comment by bradymholt** [comment]
Thank you @efranzinelli !

**Comment by bradymholt** [comment]
Fix released: https://www.nuget.org/packages/dbup-sqlserver-scripting/1.5.0
