### ISSUE TITLE
start-databasescript Error in New style Visual Studio 2017 csproj

### ISSUE THREAD

**Issue by garetharevans** [bradymholt/dbup-sqlserver-scripting#17]
I have a visual studio 2017 project with the new style csproj set to TargetFramework net461

When I try to run start-databasescript in the Package Manager Console I get an error saying :-
"The term <path to exe - but wrong> is not recognised as the name of a cmdlet, function.." etc
At C:\Users\<user>\.nuget\packages\dbup-sqlserver-scripting\1.5.0\tools\dbup-sqlserver-scripting.psm1:14 char:5

new-migration and start-migrations work correctly

The issue appears to be because the vs project defaults to build into the subfolder \bin\Debug\net461\ whereas dbup-sqlserver-scripting.psm1 seems to be hard coded to look in \bin\Debug\

I tried to change the Output Path in the vs project, but was having problems with it reverting straight back to \net461\. I finally found that there is a workaround in vs for this, adding the following to the csproj

```
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
```

So although this solves the issue for me, would it be possible for the script to detect the actual output path, so it works out of the box?

Many thanks

Visual Studio 15.4.1
dbup 3.3.5
dbup-consolescripts 1.2.3.
dbup-sqlserver-scripting 1.5.0

**Comment by bradymholt** [comment]
Thanks for the report @g1894 .  Mind taking a stab at a PR on this one?  I would surely appreciate it!
