### ISSUE TITLE
Space characters in solution path break the scripts.

### ISSUE THREAD

**Issue by digiguru** [bradymholt/dbup-sqlserver-scripting#2]
I tried to run this from a solution that has a space in the filepath, but it errors....

The full path of the solution is...

`\\vmware-host\shared  folders\Documents\Visual Studio 2013\Projects\Noodleing\`

And this is the output when I run `Start-DatabaseScript`

``` powershell
The term '\\vmware-host\shared' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:21
+ \\vmware-host\shared <<<<  folders\Documents\Visual Studio 2013\Projects\Noodleing\Noodleing\bin\Debug\Noodleing.exe --scri
ptAllDefinitions
    + CategoryInfo          : ObjectNotFound: (\\vmware-host\shared:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Could it be a result of this line of code?
https://github.com/bradyholt/dbup-sqlserver-scripting/blob/7419c84611dd91b6463149100df3877d21f85782/build/tools/dbup-sqlserver-scripting.psm1#L8

**Comment by bradymholt** [comment]
Fixed by 2c4c55207e4358f92d15543528204e8af6d7017c  . Released: https://www.nuget.org/packages/dbup-sqlserver-scripting/1.0.4
