### ISSUE TITLE
Script contains SET x get error "'CREATE/ALTER PROCEDURE' must be the first statement in a query batch."

### ISSUE THREAD

**Issue by allihandra** [bradymholt/dbup-sqlserver-scripting#24]
The db tables/sprocs/views include
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
which once scripted look like
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
So these scripts will fail when they run with:
'CREATE/ALTER PROCEDURE' must be the first statement in a query batch.
Is there a way to either add "GO" to the generated scripts do I have to manually remove this from all objects(if that is possible, not sure)?

**Comment by bradymholt** [comment]
I'm not sure I understand your issue.  So your own database set these options defined in the objects and dbup-sqlserver-scripting is scripting create/alter statements with these options but not including `GO`?  This project uses [Microsoft.SqlServer.Management.Smo](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.scriptingoptions.aspx) for scripting so there might be an [option](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.scriptingoptions.aspx) that could be set that would do what you need.  If you find the option and it makes sense, feel free to submit a PR.

**Comment by allihandra** [comment]
So I wonder if this is a sql 2017 version issue, I have not done anything "special" to add the SET stuff to my objects when I created them directly in my db, and when I use this tool which creates my object's definition scripts, the SET stuff is included (w/o GO) making the script un-runnable. Since this seems like it would be a problem for other people, the only maybe unusual factor is we upgraded to SQL 2017 maybe ?  I may not be clever enough to figure out how to fix this and I may need to globally change these generated scripts before I save them in source control. Thank you bradymholt for your response.

**Comment by allihandra** [comment]
Ok so maybe I spoke to soon, just looked at the link you gave and viola! It appears this may be something I can handle, thank you
AnsiPadding | Gets or sets a Boolean property that specifies whether the generated script contains the Transact-SQL statements SET ANSI-PADDING ON and SET ANSI-PADDING OFF before and after the CREATE TABLE statement, respectively.
-- | --

**Comment by allihandra** [comment]
You got me closer to the solution I found someone else with the same issue in smo it may be the NoCommandTerminator = $False  option I need to include;
https://social.msdn.microsoft.com/Forums/en-US/b4f51241-7c9e-494c-8148-f48e38f28c49/smo-scripting-options-how-to-get-rid-of-set-ansinulls-on-set-quotedidentifier-on?forum=sqlsmoanddmo

**Comment by kkrol** [comment]
@allihandra  Hello. Is this issue still open?
Can we close it ?

**Comment by bradymholt** [comment]
Closing this one out for now...can reopen if needed.
