### ISSUE TITLE
UpgradeEngine 

### ISSUE THREAD

**Issue by elinato** [bradymholt/dbup-sqlserver-scripting#25]
The type 'UpgradeEngine' is defined in an assembly that is not referenced. You must add a reference to assembly 'DbUp, Version=3.3.5.0, Culture=neutral, PublicKeyToken=4b419c53bdfd4cbf'

I have DBUP 4.0.1.. Are you planing to update the assembly?

**Comment by bradymholt** [comment]
I have a dependency defined for DbUp 3.3.5 here: https://github.com/bradymholt/dbup-sqlserver-scripting/blob/master/dbup-sqlserver-scripting.nuspec#L18.  Have you run `nuget restore` on your project?

**Comment by elinato** [comment]
I have updated to the last DbUp 4.0.1. That's why I get this error.

**Comment by bradymholt** [comment]
I just released 2.0.0-beta-1 as a pre-release version on NuGet that includes DbUp 4.1.0.0: https://www.nuget.org/packages/dbup-sqlserver-scripting/2.0.0-beta-1.  Can you give it a try and let me know how it goes?

**Comment by elinato** [comment]
It works now. I installed DbUp 4.1.0 and sqlserver-scripting 2.0.0-beta-1 😄
