### ISSUE TITLE
Option to create batch seperator (GO) between statements

### ISSUE THREAD

**Issue by crazycrank** [bradymholt/dbup-sqlserver-scripting#28]
It's currently not possible, to create definition files which separate different batch statements with a batch separator (GO). I would create a pull request to implement that, but im not sure, how I should go about creating an option for this use case.

If you can give me a little input how I should do that (maybe similiar to the --scriptAllDefinitions Parameter?) i would create a pull request for this.

Regards
Max

**Comment by grijal** [comment]
I have created a fork with this change at https://github.com/grijal/dbup-sqlserver-scripting. Can I create a pull request?

**Comment by bradymholt** [comment]
@grijal Sure, I took a look and that looks like a good change.  Feel free to create a PR.

**Comment by crazycrank** [comment]
I'd actually think it would be cleaner to create a new flag "ScriptBatchTerminator" in the Option class itself.
ScriptingOptions is a Microsoft class and provides many different flags which aren't checked inside the dbup scripter, which could lead to confusing behavior.
Otherwise that's basically what I had in mind
