### ISSUE TITLE
Object scripting doesn't seem to run normally

### ISSUE THREAD

**Issue by omnibs** [bradymholt/dbup-sqlserver-scripting#3]
Hi, found your blog post (also a happy YNAB user =]) and tried following the steps to generate object definitions.

```
PM> install-package dbup-sqlserver-scripting
Attempting to gather dependencies information for package 'dbup-sqlserver-scripting.1.0.4' with respect to project 'DbUpTest1', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'dbup-sqlserver-scripting.1.0.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'dbup-sqlserver-scripting.1.0.4'
Resolved actions to install package 'dbup-sqlserver-scripting.1.0.4'
Adding package 'dbup.3.2.1' to folder 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages'
Added package 'dbup.3.2.1' to folder 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages'
Added package 'dbup.3.2.1' to 'packages.config'
Successfully installed 'dbup 3.2.1' to DbUpTest1
Adding package 'dbup-consolescripts.1.0.9', which only has tools group, to project 'DbUpTest1'
Adding package 'dbup-consolescripts.1.0.9' to folder 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages'
Added package 'dbup-consolescripts.1.0.9' to folder 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages'
Added package 'dbup-consolescripts.1.0.9' to 'packages.config'
Executing script file 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages\dbup-consolescripts.1.0.9\tools\init.ps1'
Successfully installed 'dbup-consolescripts 1.0.9' to DbUpTest1
Adding package 'Unofficial.Microsoft.SQLServer.SMO.2014.12.0.2000.8' to folder 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages'
Added package 'Unofficial.Microsoft.SQLServer.SMO.2014.12.0.2000.8' to folder 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages'
Added package 'Unofficial.Microsoft.SQLServer.SMO.2014.12.0.2000.8' to 'packages.config'
Successfully installed 'Unofficial.Microsoft.SQLServer.SMO.2014 12.0.2000.8' to DbUpTest1
Adding package 'dbup-sqlserver-scripting.1.0.4' to folder 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages'
Added package 'dbup-sqlserver-scripting.1.0.4' to folder 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages'
Added package 'dbup-sqlserver-scripting.1.0.4' to 'packages.config'
Executing script file 'C:\Users\Juliano\documents\visual studio 2015\Projects\DbUpTest1\packages\dbup-sqlserver-scripting.1.0.4\tools\init.ps1'
Successfully installed 'dbup-sqlserver-scripting 1.0.4' to DbUpTest1
```

Pasted the `int Main` from the `README.md` file.

Tried running `Start-DatabaseScript` pointing to an existing database:

```
PM> Start-DatabaseScript
Building...
Fetching list of already executed scripts.
The [SchemaVersions] table could not be found. The database is assumed to be at version 0.
Beginning database upgrade
Fetching list of already executed scripts.
The [SchemaVersions] table could not be found. The database is assumed to be at version 0.
No new scripts need to be executed - completing.
Success!
```

Nothing showed up, no folders were created, so I thought "maybe I have to create a migration first, which makes no sense since I'm starting with an existing database but oh well".

```
PM> New-Migration
Created new migration: 160111174724.sql
PM> Start-DatabaseScript
Building...
Fetching list of already executed scripts.
The [SchemaVersions] table could not be found. The database is assumed to be at version 0.
Beginning database upgrade
Fetching list of already executed scripts.
The [SchemaVersions] table could not be found. The database is assumed to be at version 0.
Executing SQL Server script 'DbUpTest1.Scripts.160111174724.sql'
Creating the [SchemaVersions] table
The [SchemaVersions] table has been created
Upgrade successful
Success!
```

Still nothing... so I dug around the source code and found that `ScriptAll` is called when `args` has `--scriptAllDefinitions`, so I added it:

```
var result = upgradeScriptingEngine.Run(new [] { "--scriptAllDefinitions" });
```

Tried `Start-DatabaseScript` and voila! It works. All my stuff got dumped. But why only when I set `--scriptAllDefinitions`?

Maybe it kickstarted the whole thing, IDK, so I took out the hardcoded --scriptAllDefs, created a migration with a simple table and ran Start-Migrations. Scripting definitions didn't run again.

```
PM> Start-Migrations
Building...
Fetching list of already executed scripts.
Beginning database upgrade
Fetching list of already executed scripts.
Executing SQL Server script 'DbUpTest1.Scripts.160111175327.sql'
Upgrade successful
Success!
```

My table got created on the target database but it was not written to the `Defitions\Tables` folder.

I tried putting back the --scriptalldefs arg but then no migrations are executed, I'm forcing some Dump-Only mode.

Halp?

**Comment by sepal7** [comment]
Hi, I have the same problem as the above:

New-Migration was successfully executed from PM console and the table is created in the DB, **but the database definitions were not written to anywhere in the project folder (file system)**. 

It was a Create Table script inside a C# Console App. (VS Prof 2013.4, SQL 2008 R2 SP3)

Note, it is not a new database, did the above in an existing database.

PFB step and details:
1. PM> New-Migration
   Created new migration: 160121093356.sql
2. Saved the above SQL file with:
   Create table Test (Id int)
3. PM> Start-Migrations
   Building...
   Fetching list of already executed scripts.
   Beginning database upgrade
   Fetching list of already executed scripts.
   Executing SQL Server script 'xx.Scripts.160121093356.sql'
   Upgrade successful
   Success!
4. Table is created in DB but couldn't find the database definitions anywhere in the project folder (file system). :worried:

**Comment by aseniah** [comment]
I have this same issue (migrations work, but no definitions folder or scripts generated). I'm in the process of switching from EF Migrations to DbUp and this package would be extremely helpful for my team. Looking forward to a resolution.

**Comment by omnibs** [comment]
I have just confirmed the latest release fixed the issue and it works now. =]

I'll be happy to abandon Database Projects!

**Comment by bradymholt** [comment]
Great to hear!

**Comment by bradymholt** [comment]
@omnibs Also, glad to hear you're a happy @ynab user!
