### ISSUE TITLE
Refreshing solution explorer

### ISSUE THREAD

**Issue by nskerl** [bradymholt/dbup-sqlserver-scripting#7]
Have you found a way to have the generated .sql file included in the project so it is immediately visible in Solution Explorer without manually right-clicking / include in project every time?

This approach gets close but still requires a refresh of the explorer:

```
<ItemGroup>
    <Content Include="Definitions\**\*.sql" />
</ItemGroup>
```

**Comment by nskerl** [comment]
Actually, just saw in your video how this is intentional. Maybe this is something we can add as a switch to the  Start-Migrations cmd?

**Comment by bradymholt** [comment]
Actually, I am totally open to having these included in the project by default.  I would surely welcome a PR that does it.
