### ISSUE TITLE
scripting triggers

### ISSUE THREAD

**Issue by pritesh3** [bradymholt/dbup-sqlserver-scripting#8]
Hi,
I would really like to be able to generate and maintain scripts for table triggers. 

Anyone know how I can do that? 

Thank you.

**Comment by bradymholt** [comment]
I believe SQL Server SMO exposes `Triggers` on the database object.  So, an item could be added here: https://github.com/bradyholt/dbup-sqlserver-scripting/blob/master/DbUp.Support.SqlServer.Scripting/DbObjectScripter.cs#L136 to initiate scripting the triggers and then the method that handles it would just need to iterate on `foreach (Table table in context.Database.Triggers)`.  (maybe?)

**Comment by bradymholt** [comment]
Added here: https://github.com/bradyholt/dbup-sqlserver-scripting/pull/13
